import com.lv.view.SearchResultView;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        String output = new SearchResultView().load();
        System.out.println(output);
    }
}
